let lessonOne = {
    "title": "レッスン1",
    "translations": {
      "だいがく": "university",
      "こうこう": "high school",
      "がくせい": "student",
      "だいがくせい": "university student",
      "りゅうがくせい": "international student",
      "せんせい": "teacher",
      "...ねんせい": "...th year student",
      "いちねんせい": "first year student",
      "せんこう": "major",
      "わたし": "I / me",
      "ともだち": "friend",
      "...さん": "Mr./Ms.",
      "...じん": "person from...",
      "にほんじん": "Japanese person",
      "いま": "now",
      "ごぜん": "morning",
      "ごご": "afternoon",
      "...じ": "o'clock",
      "いちじ": "one o'clock",
      "はん": "half",
      "にじはん": "two and a half",
      "にほん": "Japan",
      "アメリカ": "America",
      "...ご": "language of...",
      "にほんご": "Japanese language",
      "...さい": "...years old",
      "でんわ": "telephone",
      "...ばん": "...number",
      "ばんごう": "number",
      "なまえ": "name",
      "なん/なに": "what",
      "あのう": "um",
      "はい": "yes",
      "そうです": "that's right",
      "そうですか": "is that so",
      "イギリス" : "Britain",
      "オーストラリア": "Australia",
      "かんこく": "South Korea",
      "かなだ": "Canada",
      "ちゅうごく": "China",
      "インド": "India",
      "エジプト": "Egypt",
      "フィリピン": "Philippines",
      "アジアけんきゅう": "Asian studies",
      "けいざい": "economics",
      "こうがく": "engineering",
      "こくさいかんけい": "international relations",
      "コンピューター": "computer",
      "せいじ": "politics",
      "せいぶつがく": "biology",
      "ビジネス": "business",
      "ぶんがく": "literature",
      "れきし": "history",
      "いしゃ": "doctor",
      "かいしゃいん": "company employee",
      "かんごし": "nurse",
      "こうこうせい": "high school student",
      "しゅふ": "housewife",
      "だいがくいんせい": "graduate student",
      "べんごし": "lawyer",
      "おかあさん": "mother",
      "おとうさん": "father",
      "おねえさん": "older sister",
      "おにいさん": "older brother",
      "いもうと": "younger sister",
      "おとうと": "younger brother"
    }
  };
let lessonTwo =  {
    "title": "レッスン2",
    "translations": {
      "これ": "this",
      "それ": "that",
      "あれ": "that (over there)",
      "どれ": "which one",
      "この": "this (specific)",
      "その": "that (specific)",
      "あの": "that (over there) (specific)",
      "どの": "which (specific)",
      "ここ": "here",
      "そこ": "there",
      "あそこ": "over there",
      "どこ": "where",
      "だれ": "who",
      "おいしい": "delicious",
      "さかな": "fish",
      "とんかつ": "pork cutlet",
      "にく": "meat",
      "メニュー": "menu",
      "やさい": "vegetable",
      "かさ": "umbrella",
      "かばん": "bag",
      "くつ": "shoes",
      "さいふ": "wallet",
      "じんず": "jeans",
      "じてんしゃ": "bicycle",
      "しんぶん": "newspaper",
      "スマホ": "smartphone",
      "Tシャツ": "T-shirt",
      "トーケー": "clock",
      "ノート": "notebook",
      "ペン": "pen",
      "ぼうし": "hat",
      "ほんぎんこう": "bank",
      "コンビニ": "convenience store",
      "トイレ": "toilet",
      "としょかん": "library",
      "ゆうびんきょく": "post office",
      "いるぎす": "English",
      "かんこく": "South Korea",
      "ちゅうごく": "China",
      "えいご": "English language",
      "けいざい": "economics",
      "コンピューター": "computer",
      "ビジネス": "business",
      "れきし": "history",
      "おかあさん": "mother",
      "おとうさん": "father",
      "いくら": "how much",
      "...えん": "...yen",
      "たかい": "expensive",
      "いらっしゃいませ": "welcome (used by a store/business)",
      "(...を) おねがいします": "(please) (used when making a request)",
      "(...を) ください": "(please give me) (used when ordering/requesting something)",
      "じゃあ": "well/then",
      "どうぞ": "please/go ahead",
      "どうも": "thank you"
    }
  };
  
